# v2 syntax
version: '2'

services:
  himcd:
    build:
      context: .
    container_name: himcd
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: himcd
  #     DB_HOST: himcd_mysql
  #     DB_PORT: 3306
  #     DB_USER: admin
  #     DB_PASSWORD: secret
  #     DB_NAME: himcd
  #   depends_on: 
  #     - himcd_mysql
  # himcd_mysql:
  #   image: mysql
  #   restart: always
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: secret
  #     MYSQL_DATABASE: himcd