# v2 syntax
version: '2'

services:
  himcd:
    build:
      context: .
    container_name: himcd
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=8889
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=himcd